# Generated by Django 6.0.3 on 2026-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
